import type { Metadata } from "next";
import { Indie_Flower, Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const indie_flower = Indie_Flower({ subsets: ["latin"], weight: "400", variable: '--font-indie-flower' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${indie_flower.variable}`}>
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html >
  );
}
